export const COMUNIDADES_FLAGS = {
    1: 'https://upload.wikimedia.org/wikipedia/commons/1/16/Flag_of_the_Valencian_Community_%282x3%29.svg',
    2: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_Andaluc%C3%ADa.svg',
    3: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Flag_of_Aragon.svg',
    4: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_Asturias.svg',
    5: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Flag_of_the_Balearic_Islands.svg',
    6: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Flag_of_the_Canary_Islands.svg',
    7: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Cantabria_%28Official%29.svg',
    8: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Flag_of_Castile_and_Le%C3%B3n.svg',
    9: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Bandera_Castilla-La_Mancha.svg',
    10: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Catalonia.svg',
    11: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Flag_of_Extremadura%2C_Spain_%28with_coat_of_arms%29.svg',
    12: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Galicia.svg',
    13: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_the_Community_of_Madrid.svg',
    14: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Flag_of_the_Region_of_Murcia.svg',
    15: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Bandera_de_Reino_de_Navarra.svg',
    16: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/Flag_of_the_Basque_Country.svg',
    17: 'https://upload.wikimedia.org/wikipedia/commons/d/db/Flag_of_La_Rioja_%28with_coat_of_arms%29.svg',
    18: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Ceuta.svg',
    19: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Flag_of_Melilla.svg',
  };
  